### PR TITLE
Changable Duration for Spinning Icons

### LINKED ISSUE #16: Changable Duration for Spinning Icons
It would be nice to change the Duration (default 1s) of `ISpinable` control via a new `DependencyProperty`.

### PR DESCRIPTION
**Pull request by punker76**
Add an attached dependency property to set the spinning animation duration.

This Fixes  #16 Changable Duration for Spinning Icons

### CODE REVIEW

**Comment by punker76** [comment]
@charri this property can maybe directly implemented for the ISpinnable interface. what do you think?

**Comment by punker76** [comment]
@charri busy or is this repo dead?

**Comment by TrabacchinLuigi** [comment]
@punker76  i hope not!

**Comment by charri** [comment]
@punker76 - Sorry for the delay, currently very busy:
busy

I will look at the pull-request asap :), thanks for being so patient

**Comment by punker76** [comment]
@charri will do that now.

one thing

> this property can maybe directly implemented for the ISpinnable interface. what do you think?

**Comment by charri** [comment]
not sure i understand the question. how can you implement the property in the ISpinnable interface?

**Comment by punker76** [comment]
@charri i mean, this attached property can be implemented directly as dependency property in `FontAwesome` and `ImageAwesome` (ok its a little bit boilerplate code)

```csharp
    public interface ISpinable
    {
        /// <summary>
        /// Gets or sets the current spin (angle) animation of the icon.
        /// </summary>
        bool Spin { get; set; }

        /// <summary>
        /// Gets/Sets the duration of the spinning animation (in seconds). This will stop and start the spin animation.
        /// </summary>
        double SpinDuration { get; set; }
    }
```

**Comment by charri** [comment]
good idea, then it can be directly accessed as a property in the FontAwesome class

**Comment by punker76** [comment]
@charri this one...

```xaml
        /// <summary>
        /// Identifies the FontAwesome.WPF.ImageAwesome.Spin dependency property.
        /// </summary>
        public static readonly DependencyProperty SpinDurationProperty =
            DependencyProperty.Register("SpinDuration", typeof(double), typeof(ImageAwesome), new PropertyMetadata(1d, SpinDurationChanged, SpinDurationCoerceValue));

        /// <summary>
        /// Gets or sets the duration of the spinning animation (in seconds). This will stop and start the spin animation.
        /// </summary>
        public double SpinDuration
        {
            get { return (double)GetValue(SpinProperty); }
            set { SetValue(SpinProperty, value); }
        }

        private static void SpinDurationChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var imageAwesome = d as ImageAwesome;

            if (null == imageAwesome || !imageAwesome.Spin || !(e.NewValue is double) || e.NewValue.Equals(e.OldValue)) return;

            imageAwesome.StopSpin();
            imageAwesome.BeginSpin();
        }
```

**Comment by charri** [comment]
:+1:

**Comment by punker76** [comment]
@charri done

**Comment by charri** [comment]
that was fast!

I will do nuget push tomorrow/friday.

**Pull request merged**
