### PR TITLE
Added click event support for the components.

### PR DESCRIPTION
**Pull request by erenhatirnaz**

### CODE REVIEW

**Comment by charri** [comment]
Thanks for you contribution.

what is the use-case for clickable images / textblocks? Would it not be better to put them inside "clickable" elements - such as Button etc?

**Comment by erenhatirnaz** [comment]
You're welcome.
Yes, you're right but I think it would be more useful that way.

**Comment by TrabacchinLuigi** [comment]
This seems odd to me, it is more code to mantain to do the same thing that you can achieve nesting it in the clikable element... More code to mantain more bug, more problems

**Comment by erenhatirnaz** [comment]
I analyzed a bit more and i think you are right, so you can close the pull request.

**Comment by charri** [comment]
I looked up in the fontawesome documentation what it says about clickable icons and it is advised to be put into <a> or <button> tags etc. Therefor we should do the same, so that it seems more coherent with the official fontawesome lib.
Again, thanks for your pull request but I'll be closing it here.

**Pull request closed without merging**
