### PR TITLE
Add Awesome.Content attached dependency property

### PR DESCRIPTION
**Pull request by BrainCrumbz**
Also, update Example project dependency from Nuget package

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
hello. Have you got any chance to take a look at this PR? What do you think about it? We found that useful.

**Comment by charri** [comment]
@BrainCrumbz  Thank you for the interest in my repo and your pull request. Sorry, the last week(s) have just been crazy. I've gone over your pull request in detail and added my remarks directly to the pull request. Let me know what you think.

**Comment by BrainCrumbz** [comment]
You're welcome. No prob with the nesting and dead code. I guess it's more something of *taste*, so to say, but it's ok. Will change that. Please see the feedback on your first comment about FontFamily.

**Comment by charri** [comment]
Will be pushing to nuget tonight. Thanks again.

**Comment by BrainCrumbz** [comment]
Great. What about that FontFamily thing (see comments above this thread)? The idea seems right, but the implementation not as much.

**Comment by charri** [comment]
It is certainly a tough call and I thought about it long and hard. Setting another DependencyProperty could be considered a code-smell. On the other hand it would certainly reduce duplicate code.
Until someone suggests a better method, I think it’s best to keep it as it is.

**Comment by charri** [comment]
@BrainCrumbz Package has been pushed to v4.3.0.4  https://www.nuget.org/packages/FontAwesome.WPF/4.3.0.4 - v4.3.0.3 was already pushed but not referenced in github

**Comment by BrainCrumbz** [comment]
:+1:

**Pull request merged**
